create extension if not exists pgcrypto;

do $$ begin create type public.app_role as enum ('admin','staff','customer'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('pending','confirmed','processing','ready','shipped','delivered','cancelled','returned'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('unpaid','paid','refunded'); exception when duplicate_object then null; end $$;

create table if not exists public.user_roles(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,role public.app_role not null default 'customer',created_at timestamptz not null default now(),unique(user_id,role));
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text default '',category_id uuid references public.categories(id) on delete set null,price numeric(10,2) not null default 0,stock int not null default 0,image_url text,is_featured boolean not null default false,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.customers(id uuid primary key default gen_random_uuid(),user_id uuid unique references auth.users(id) on delete set null,full_name text not null,phone text,email text,city text,address text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_number text unique not null, user_id uuid references auth.users(id) on delete set null,customer_id uuid references public.customers(id) on delete set null,customer_name text not null,customer_phone text not null,customer_email text,city text,address text,occasion text,event_date date,status public.order_status default 'pending',payment_status public.payment_status default 'unpaid',payment_method text default 'cod',subtotal numeric(10,2) default 0,shipping_fee numeric(10,2) default 0,discount numeric(10,2) default 0,total numeric(10,2) default 0,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id) on delete cascade,product_id uuid references public.products(id),name text not null,unit_price numeric(10,2) default 0,quantity int default 1,total numeric(10,2) default 0,created_at timestamptz default now());
create table if not exists public.custom_designs(id uuid primary key default gen_random_uuid(),reference text unique not null,user_id uuid references auth.users(id) on delete set null,occasion text,favor_type text,quantity int default 1,palette text,inscription text,event_date date,extras text,contact_name text,contact_phone text,status text default 'submitted',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),product_id uuid references public.products(id) on delete cascade,author_name text not null,rating int check(rating between 1 and 5),body text not null,is_approved boolean default false,created_at timestamptz default now());
create table if not exists public.coupons(id uuid primary key default gen_random_uuid(),code text unique not null,discount_type text default 'percent',amount numeric(10,2) default 0,usage_limit int,used_count int default 0,is_active boolean default true,expires_at timestamptz);
create table if not exists public.settings(key text primary key,value jsonb not null default '{}',updated_at timestamptz default now());

create or replace function public.is_staff(uid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=uid and role in ('admin','staff')); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.customers(user_id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),new.email) on conflict(user_id) do nothing; insert into public.user_roles(user_id,role) values(new.id,'customer') on conflict do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.user_roles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.customers enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.custom_designs enable row level security; alter table public.reviews enable row level security; alter table public.coupons enable row level security; alter table public.settings enable row level security;

drop policy if exists categories_public_read on public.categories; create policy categories_public_read on public.categories for select to anon,authenticated using(is_active or public.is_staff(auth.uid()));
drop policy if exists categories_staff_write on public.categories; create policy categories_staff_write on public.categories for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists products_public_read on public.products; create policy products_public_read on public.products for select to anon,authenticated using(is_active or public.is_staff(auth.uid()));
drop policy if exists products_staff_write on public.products; create policy products_staff_write on public.products for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists roles_self on public.user_roles; create policy roles_self on public.user_roles for select to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid()));
drop policy if exists roles_admin on public.user_roles; create policy roles_admin on public.user_roles for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists customers_self on public.customers; create policy customers_self on public.customers for select to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid()));
drop policy if exists customers_insert on public.customers; create policy customers_insert on public.customers for insert to authenticated with check(user_id=auth.uid() or public.is_staff(auth.uid()));
drop policy if exists customers_update on public.customers; create policy customers_update on public.customers for update to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid())) with check(user_id=auth.uid() or public.is_staff(auth.uid()));
drop policy if exists orders_insert on public.orders; create policy orders_insert on public.orders for insert to anon,authenticated with check(true);
drop policy if exists orders_read on public.orders; create policy orders_read on public.orders for select to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid()));
drop policy if exists orders_staff_update on public.orders; create policy orders_staff_update on public.orders for update to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists order_items_insert on public.order_items; create policy order_items_insert on public.order_items for insert to anon,authenticated with check(true);
drop policy if exists order_items_read on public.order_items; create policy order_items_read on public.order_items for select to authenticated using(public.is_staff(auth.uid()) or exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
drop policy if exists designs_insert on public.custom_designs; create policy designs_insert on public.custom_designs for insert to anon,authenticated with check(true);
drop policy if exists designs_read on public.custom_designs; create policy designs_read on public.custom_designs for select to authenticated using(user_id=auth.uid() or public.is_staff(auth.uid()));
drop policy if exists designs_update on public.custom_designs; create policy designs_update on public.custom_designs for update to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists reviews_public on public.reviews; create policy reviews_public on public.reviews for select to anon,authenticated using(is_approved or public.is_staff(auth.uid()));
drop policy if exists reviews_insert on public.reviews; create policy reviews_insert on public.reviews for insert to anon,authenticated with check(is_approved=false);
drop policy if exists reviews_staff on public.reviews; create policy reviews_staff on public.reviews for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists coupons_public on public.coupons; create policy coupons_public on public.coupons for select to anon,authenticated using(is_active or public.is_staff(auth.uid()));
drop policy if exists coupons_staff on public.coupons; create policy coupons_staff on public.coupons for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));
drop policy if exists settings_public on public.settings; create policy settings_public on public.settings for select to anon,authenticated using(true);
drop policy if exists settings_staff on public.settings; create policy settings_staff on public.settings for all to authenticated using(public.is_staff(auth.uid())) with check(public.is_staff(auth.uid()));

insert into categories(slug,name) values('wedding','زفاف'),('engagement','خطوبة'),('katb','كتب كتاب'),('henna','حنة'),('newborn','مولود وسبوع'),('babyshower','بيبي شاور'),('graduation','تخرج'),('birthday','عيد ميلاد'),('custom','مناسبات خاصة') on conflict(slug) do nothing;
insert into products(slug,name,description,category_id,price,stock,image_url,is_featured) select 'pearl-blush-jar','برطمان اللؤلؤ الوردي','برطمان أكريليك أنيق بلمسة وردية وبطاقة شخصية.',id,14,120,'/src/assets/product-1.jpg',true from categories where slug='engagement' on conflict(slug) do nothing;
insert into products(slug,name,description,category_id,price,stock,image_url,is_featured) select 'soft-newborn-box','علبة السبوع الناعمة','علبة صغيرة ناعمة بفيونكة وتفاصيل لطيفة.',id,11,150,'/src/assets/product-2.jpg',true from categories where slug='newborn' on conflict(slug) do nothing;
insert into products(slug,name,description,category_id,price,stock,image_url,is_featured) select 'henna-ornate-box','صندوق الحنة المزخرف','تفاصيل شرقية فاخرة بدرجات الأحمر والذهبي.',id,16,80,'/src/assets/product-3.jpg',true from categories where slug='henna' on conflict(slug) do nothing;
insert into products(slug,name,description,category_id,price,stock,image_url,is_featured) select 'rose-gold-box','بوكس الورد والذهب','بوكس هدية كبير بلمسات روز جولد وزهور.',id,240,20,'/src/assets/product-4.jpg',true from categories where slug='wedding' on conflict(slug) do nothing;
insert into settings(key,value) values('store','{"name":"Esraa Moments","currency":"ر.س","shippingFee":25,"freeShippingOver":500,"whatsapp":"","instagram":"https://www.instagram.com/esraamomentsstore","tiktok":"https://www.tiktok.com/@esraamomentsstore"}'::jsonb) on conflict(key) do nothing;

-- بعد إنشاء حساب الإدارة من Auth، نفّذ مرة واحدة:
-- insert into public.user_roles(user_id,role) values('USER_UUID_HERE','admin') on conflict do nothing;
